# Generated by Django 4.2.30 on 2026-04-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor_doctorslot_doctorscheduletemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('visit_type', models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow Up')], default='NEW', max_length=20)),
                ('channel', models.CharField(choices=[('WALK_IN', 'Walk-In'), ('ONLINE', 'Online'), ('PHONE', 'Phone')], default='WALK_IN', max_length=20)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BOOK', 'Book'), ('RESCHEDULE', 'Reschedule'), ('CANCEL', 'Cancel')], max_length=20)),
                ('previous_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('actor_username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.appointment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
