# Generated by Django 4.2.30 on 2026-04-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_appointmentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('token_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SKIPPED', 'Skipped'), ('NO_SHOW', 'No Show')], default='WAITING', max_length=20)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='core.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='core.doctor')),
            ],
            options={
                'ordering': ['slot_date', 'token_number'],
                'unique_together': {('doctor', 'slot_date', 'token_number')},
            },
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CALL_NEXT', 'Call Next'), ('SKIP', 'Skip'), ('RECALL', 'Recall'), ('NO_SHOW', 'No Show')], max_length=20)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('actor_username', models.CharField(max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.queueitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
