# Generated by Django 4.2.30 on 2026-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prescription_medicalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='clinic_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='clinic_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_qualification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_reg_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_age_at_issue',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='rx_number',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='special_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='validity_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
