# Generated by Django 4.2.30 on 2026-04-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_prescription_clinic_address_prescription_clinic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead Letter')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_handoff', to='core.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_handoffs', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingRetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('outcome', models.CharField(max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('actor_username', models.CharField(blank=True, default='system', max_length=150)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_logs', to='core.billinghandoff')),
            ],
            options={
                'ordering': ['attempted_at'],
            },
        ),
    ]
