# Generated by Django 4.2.30 on 2026-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_billinghandoff_billingretrylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='opd_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentevent',
            name='action',
            field=models.CharField(choices=[('BOOK', 'Book'), ('RESCHEDULE', 'Reschedule'), ('COMPLETE', 'Complete'), ('CANCEL', 'Cancel')], max_length=20),
        ),
    ]
