# Generated by Django 4.2.30 on 2026-04-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appointment_opd_number_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=150)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF')], max_length=10)),
                ('filters', models.JSONField(default=dict)),
                ('artifact_name', models.CharField(max_length=255)),
                ('artifact_content', models.TextField()),
                ('status', models.CharField(choices=[('GENERATED', 'Generated')], default='GENERATED', max_length=20)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GENERATE', 'Generate'), ('DOWNLOAD', 'Download')], max_length=20)),
                ('actor_username', models.CharField(max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.reportexport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
