# Generated by Django 4.2.30 on 2026-04-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reportexport_reportexportaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('observed_value', models.FloatField()),
                ('threshold_value', models.FloatField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warn'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warn'), ('CRITICAL', 'Critical')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('runbook_ref', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
