# Generated by Django 4.2.30 on 2026-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='daily_patient_capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
