# Generated by Django 4.2.30 on 2026-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_patient_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='known_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
