# Generated by Django 4.2.30 on 2026-05-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_patient_known_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorscheduletemplate',
            name='daily_patient_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
