# Generated by Django 4.2.30 on 2026-05-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_doctorscheduletemplate_daily_patient_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='reg_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
