# Generated by Django 4.2.30 on 2026-05-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_doctor_reg_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opd_number', models.CharField(max_length=30, unique=True)),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow Up')], default='NEW', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FINALIZED', 'Finalized')], default='OPEN', max_length=20)),
                ('repeat_fee_decision', models.CharField(choices=[('PENDING', 'Pending'), ('YES', 'Yes'), ('NO', 'No')], default='PENDING', max_length=20)),
                ('repeat_fee_reason', models.CharField(blank=True, default='', max_length=255)),
                ('finalized_by', models.CharField(blank=True, default='', max_length=150)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=150)),
                ('updated_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_ledgers', to='core.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_ledgers', to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_ledgers', to='core.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.billingledger')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('actor_username', models.CharField(max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.billingledger')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('OPD_NEW_FEE', 'OPD New Fee'), ('OPD_REPEAT_FEE', 'OPD Repeat Fee'), ('MANUAL', 'Manual')], max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_order_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.billingledger')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ledger', 'line_type'], name='core_billin_ledger__e2d4d8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='billingledger',
            index=models.Index(fields=['status'], name='core_billin_status_c2a9f3_idx'),
        ),
    ]
