# Generated by Django 4.2.30 on 2026-05-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_clinicsettings_logo_prescription_clinic_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='opd_existing_patient_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='opd_new_patient_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billinglineitem',
            name='line_type',
            field=models.CharField(choices=[('OPD_NEW_FEE', 'OPD New Fee'), ('OPD_REPEAT_FEE', 'OPD Repeat Fee'), ('LAB', 'Lab / Pathology'), ('RADIOLOGY', 'Radiology / Imaging'), ('PHARMACY', 'Pharmacy / Medicine'), ('PROCEDURE', 'Procedure Charges'), ('MISC', 'Miscellaneous'), ('MANUAL', 'Manual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='queueevent',
            name='action',
            field=models.CharField(choices=[('CALL_NEXT', 'Call Next'), ('SKIP', 'Skip'), ('RECALL', 'Recall'), ('COMPLETE', 'Complete'), ('NO_SHOW', 'No Show')], max_length=20),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SKIPPED', 'Skipped'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='WAITING', max_length=20),
        ),
    ]
