# Generated by Django 4.2.30 on 2026-05-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_billingledger_opd_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='clinic_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
