# Generated by Django 4.2.30 on 2026-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_clinicsettings_clinic_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='clinic_mob',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
