# Generated by Django 4.2.30 on 2026-05-09 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_clinicsettings_clinic_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='marked_emergency_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='marked_emergency_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_appointments_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_consultations', to='core.doctor'),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='resume_order_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('PAUSED', 'Paused'), ('RESUMED', 'Resumed'), ('SKIPPED', 'Skipped'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='WAITING', max_length=20),
        ),
    ]
