# Generated by Django 4.2.30 on 2026-05-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_billinglineitem_rct_recovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinglineitem',
            name='line_type',
            field=models.CharField(choices=[('OPD_NEW_FEE', 'OPD New Fee'), ('OPD_REPEAT_FEE', 'OPD Repeat Fee'), ('LAB', 'Lab / Pathology'), ('RADIOLOGY', 'Radiology / Imaging'), ('PHARMACY', 'Pharmacy / Medicine'), ('PROCEDURE', 'Procedure Charges'), ('MISC', 'Miscellaneous'), ('MANUAL', 'Manual'), ('RCT', 'RCT')], max_length=30),
        ),
    ]
