# Generated by Django 4.2.30 on 2026-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_rct_line_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow Up'), ('FOLLOW_UP_RCT', 'Follow Up (RCT)')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingledger',
            name='visit_type',
            field=models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow Up'), ('FOLLOW_UP_RCT', 'Follow Up (RCT)')], default='NEW', max_length=20),
        ),
    ]
