# Generated by Django 4.2.30 on 2026-05-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_medicine_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billingledger',
            new_name='idx_ledger_status',
            old_name='core_billin_status_c2a9f3_idx',
        ),
        migrations.RenameIndex(
            model_name='billinglineitem',
            new_name='idx_lineitem_ledger_line_type',
            old_name='core_billin_ledger__e2d4d8_idx',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient_id', 'slot_date', 'status'], name='idx_appt_patient_date_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor_id', 'slot_date', 'status', 'start_time'], name='idx_appt_dr_date_stat_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['slot_date', 'status'], name='idx_appt_slot_date_status'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='idx_appt_created_at'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['created_at'], name='idx_invoice_created_at'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['payment_status', 'created_at'], name='idx_invoice_status_created'),
        ),
        migrations.AddIndex(
            model_name='billinginvoice',
            index=models.Index(fields=['ledger_id'], name='idx_invoice_ledger'),
        ),
        migrations.AddIndex(
            model_name='billingledger',
            index=models.Index(fields=['patient_id', 'visit_date'], name='idx_ledger_patient_visit'),
        ),
        migrations.AddIndex(
            model_name='billingledger',
            index=models.Index(fields=['doctor_id', 'visit_date', 'status'], name='idx_ledger_doctor_visit_status'),
        ),
        migrations.AddIndex(
            model_name='billingledger',
            index=models.Index(fields=['appointment_id'], name='idx_ledger_appointment'),
        ),
        migrations.AddIndex(
            model_name='billingledger',
            index=models.Index(fields=['created_at'], name='idx_ledger_created_at'),
        ),
        migrations.AddIndex(
            model_name='billinglineitem',
            index=models.Index(fields=['ledger_id', 'created_at'], name='idx_lineitem_ledger_created'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='idx_patient_phone'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='idx_patient_name'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='idx_patient_created_at'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient_id', 'issued_at'], name='idx_rx_patient_issued'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor_id', 'issued_at'], name='idx_rx_doctor_issued'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation_id'], name='idx_rx_consultation'),
        ),
        migrations.AddIndex(
            model_name='queueitem',
            index=models.Index(fields=['doctor_id', 'slot_date', 'status', 'token_number'], name='idx_queue_dr_date_stat_tok'),
        ),
    ]
