# Generated by Django 4.2.30 on 2026-05-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_phase1_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginvoice',
            name='current_visit_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='searchable_full_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=205),
        ),
    ]
