# Generated by Django 4.2.30 on 2026-05-12 18:32

from django.db import migrations
from decimal import Decimal
from collections import defaultdict


def backfill_searchable_full_name(apps, schema_editor):
    """Populate searchable_full_name for all existing patients in batches."""
    Patient = apps.get_model("core", "Patient")
    batch_size = 500
    total = 0
    ids = list(Patient.objects.values_list("id", flat=True))
    for i in range(0, len(ids), batch_size):
        batch_ids = ids[i:i + batch_size]
        batch = list(Patient.objects.filter(id__in=batch_ids))
        for patient in batch:
            patient.searchable_full_name = f"{patient.first_name} {patient.last_name}".strip().lower()
        Patient.objects.bulk_update(batch, ["searchable_full_name"])
        total += len(batch)
    print(f"  Backfilled searchable_full_name for {total} patients")


def backfill_current_visit_total(apps, schema_editor):
    """
    For FOLLOW_UP_RCT invoices with a paid previous bill, compute and store
    current_visit_total. For all other invoices set it equal to total.
    """
    BillingInvoice = apps.get_model("core", "BillingInvoice")
    BillingLineItem = apps.get_model("core", "BillingLineItem")

    all_invoices = list(
        BillingInvoice.objects.select_related("ledger").all()
    )

    rct_invoices = [inv for inv in all_invoices if inv.ledger.visit_type == "FOLLOW_UP_RCT"]
    non_rct = [inv for inv in all_invoices if inv.ledger.visit_type != "FOLLOW_UP_RCT"]

    # Non-RCT: current_visit_total == total
    batch_size = 500
    for i in range(0, len(non_rct), batch_size):
        batch = non_rct[i:i + batch_size]
        for inv in batch:
            inv.current_visit_total = inv.total
        BillingInvoice.objects.bulk_update(batch, ["current_visit_total"])

    # RCT invoices: compute properly
    if rct_invoices:
        patient_ids = list({inv.ledger.patient_id for inv in rct_invoices})
        prev_candidates = list(
            BillingInvoice.objects.select_related("ledger")
            .filter(ledger__patient_id__in=patient_ids)
            .order_by("ledger__patient_id", "-created_at")
        )
        prev_map = defaultdict(list)
        for inv in prev_candidates:
            prev_map[inv.ledger.patient_id].append(inv)

        all_ledger_ids = set()
        for inv in rct_invoices:
            all_ledger_ids.add(inv.ledger.id)
            for c in prev_map.get(inv.ledger.patient_id, []):
                if c.created_at < inv.created_at and c.id != inv.id:
                    all_ledger_ids.add(c.ledger.id)
                    break

        items_by_ledger = {}
        for item in BillingLineItem.objects.filter(ledger_id__in=all_ledger_ids).order_by("ledger_id", "created_at"):
            items_by_ledger.setdefault(item.ledger_id, []).append(item)

        for inv in rct_invoices:
            prev = None
            for c in prev_map.get(inv.ledger.patient_id, []):
                if c.created_at < inv.created_at and c.id != inv.id:
                    prev = c
                    break
            if not prev or prev.payment_status != "DONE":
                inv.current_visit_total = inv.total
            else:
                n_cloned = len(items_by_ledger.get(prev.ledger.id, []))
                all_items = items_by_ledger.get(inv.ledger.id, [])
                current_items = all_items[n_cloned:]
                inv.current_visit_total = sum(
                    (item.amount or Decimal("0")) for item in current_items
                )
        BillingInvoice.objects.bulk_update(rct_invoices, ["current_visit_total"])

    print(f"  Backfilled current_visit_total for {len(all_invoices)} invoices")


def reverse_backfill(apps, schema_editor):
    Patient = apps.get_model("core", "Patient")
    BillingInvoice = apps.get_model("core", "BillingInvoice")
    Patient.objects.all().update(searchable_full_name="")
    BillingInvoice.objects.all().update(current_visit_total=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_phase2_denormalization'),
    ]

    operations = [
        migrations.RunPython(
            backfill_searchable_full_name,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            backfill_current_visit_total,
            reverse_code=reverse_backfill,
        ),
    ]
