from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    appointment_book_form,
    appointments_stats,
    appointment_book,
    appointment_cancel,
    appointment_complete,
    appointment_complete_after_prescription,
    appointment_add_emergency,
    doctor_day_unavailable_reschedule,
    appointment_pause_current,
    appointment_reschedule,
    appointment_next_token,
    billing_handoff_create,
    billing_handoff_reconcile,
    billing_handoff_send,
    billing_invoice_pdf_download,
    billing_invoice_print,
    billing_invoice_get,
    billing_invoice_mark_paid_upi,
    billing_invoice_live_feed,
    billing_invoice_history_by_patient,
    billing_invoice_void,
    billing_invoice_update,
    billing_ledger_add_line_item,
    billing_ledger_remove_line_item,
    billing_ledger_get_rct_case_amount,
    billing_ledger_by_opd_create,
    billing_ledger_by_opd_get,
    billing_ledger_finalize,
    billing_ledger_repeat_fee_decision,
    consultation_amend,
    consultation_amendment_history,
    consultation_finalize,
    consultation_get,
    consultation_context,
    consultation_save_draft,
    clinic_settings_update,
    health,
    health_live,
    health_ready,
    home,
    medical_order_create,
    medical_order_create_for_patient,
    medical_order_list,
    patient_medical_order_context,
    patient_register,
    patient_register_form,
    patient_edit_form,
    patient_reminder_form,
    doctor_schedule_form,
    doctor_opd_fee_update,
    patient_detail,
    patient_known_history_update,
    patient_opd_history_view,
    patient_search,
    patient_update,
    incident_create_view,
    incident_list_view,
    incident_resolve_view,
    observability_snapshot_view,
    report_export_download,
    report_export_generate,
    report_export_list,
    prescription_print,
    prescription_get,
    prescription_history_by_patient,
    prescription_issue,
    prescription_update,
    pharmacist_workbench,
    queue_board,
    queue_call_next,
    queue_mark_called,
    queue_no_show,
    queue_recall,
    queue_skip,
    receptionist_today_appointments_board,
    receptionist_pending_day_reschedules,
    receptionist_decide_day_reschedule,
    receptionist_workbench,
    rbac_bootstrap,
    schedule_upsert,
    doctor_workbench,
    doctor_appointments_page,
    doctor_consultation_page,
    doctor_vitals_orders_page,
    doctor_prescription_page,
    doctor_queue_page,
    doctor_today_appointments,
    doctor_list,
    dashboard_daily_metrics,
    tomorrow_reminder_report_view,
    yesterday_missed_report_view,
    tomorrow_reminder_report_pdf_download_view,
    yesterday_missed_report_pdf_download_view,
    user_assign_role,
    user_create,
    user_delete,
    role_delete,
    user_profile_form,
    user_profile_get,
    user_profile_update,
    user_role_management,
    admin_doctor_profile_update,
    admin_software_reset,
    vitals_record,
    medicine_search,
    medicine_management_page,
    medicine_create,
    medicine_toggle_active,
    medicine_list_api,
)

urlpatterns = [
    path("", home, name="home"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", user_profile_form, name="user-profile-form"),
    path("health/", health, name="health"),
    path("health/live/", health_live, name="health-live"),
    path("health/ready/", health_ready, name="health-ready"),
    path("workbench/reception/", receptionist_workbench, name="workbench-reception"),
    path("workbench/doctor/", doctor_workbench, name="workbench-doctor"),
    path("doctor/appointments/", doctor_appointments_page, name="doctor-appointments"),
    path("doctor/consultation/", doctor_consultation_page, name="doctor-consultation"),
    path("doctor/vitals-orders/", doctor_vitals_orders_page, name="doctor-vitals-orders"),
    path("doctor/prescription/", doctor_prescription_page, name="doctor-prescription"),
    path("doctor/queue/", doctor_queue_page, name="doctor-queue"),
    path("workbench/pharmacy/", pharmacist_workbench, name="workbench-pharmacy"),
    path("api/rbac/bootstrap/", rbac_bootstrap, name="rbac-bootstrap"),
    path("patients/register/", patient_register_form, name="patient-register-form"),
    path("patients/edit/", patient_edit_form, name="patient-edit-form"),
    path("doctors/schedule/", doctor_schedule_form, name="doctor-schedule-form"),
    path("patients/reminder/", patient_reminder_form, name="patient-reminder-form"),
    path("appointments/book/", appointment_book_form, name="appointment-book-form"),
    path("api/appointments/stats/", appointments_stats, name="appointments-stats"),
    path("api/patients/register/", patient_register, name="patient-register"),
    path("api/patients/<int:patient_id>/update/", patient_update, name="patient-update"),
    path("api/patients/<int:patient_id>/detail/", patient_detail, name="patient-detail"),
    path("api/patients/<int:patient_id>/known-history/update/", patient_known_history_update, name="patient-known-history-update"),
    path("api/patients/<int:patient_id>/opd-history/", patient_opd_history_view, name="patient-opd-history"),
    path("api/patients/search/", patient_search, name="patient-search"),
    path("api/reports/tomorrow-patients/", tomorrow_reminder_report_view, name="report-tomorrow-patients"),
    path("api/reports/yesterday-missed/", yesterday_missed_report_view, name="report-yesterday-missed"),
    path("api/reports/tomorrow-patients/pdf/", tomorrow_reminder_report_pdf_download_view, name="report-tomorrow-patients-pdf"),
    path("api/reports/yesterday-missed/pdf/", yesterday_missed_report_pdf_download_view, name="report-yesterday-missed-pdf"),
    path("api/reports/dashboard/daily-metrics/", dashboard_daily_metrics, name="dashboard-daily-metrics"),
    path("api/reports/exports/generate/", report_export_generate, name="report-export-generate"),
    path("api/reports/exports/list/", report_export_list, name="report-export-list"),
    path("api/reports/exports/<int:export_id>/download/", report_export_download, name="report-export-download"),
    path("api/observability/snapshot/", observability_snapshot_view, name="observability-snapshot"),
    path("api/incidents/create/", incident_create_view, name="incident-create"),
    path("api/incidents/<int:incident_id>/resolve/", incident_resolve_view, name="incident-resolve"),
    path("api/incidents/list/", incident_list_view, name="incident-list"),
    path("api/doctors/schedule/upsert/", schedule_upsert, name="schedule-upsert"),
    path("api/doctors/opd-fee/update/", doctor_opd_fee_update, name="doctor-opd-fee-update"),
    path("api/medicines/search/", medicine_search, name="medicine-search"),
    path("api/medicines/list/", medicine_list_api, name="medicine-list"),
    path("api/medicines/create/", medicine_create, name="medicine-create"),
    path("api/medicines/<int:medicine_id>/toggle-active/", medicine_toggle_active, name="medicine-toggle-active"),
    path("workbench/admin/medicines/", medicine_management_page, name="admin-medicines"),
    path("api/doctors/list/", doctor_list, name="doctor-list"),
    path("api/doctors/appointments/today/", doctor_today_appointments, name="doctor-appointments-today"),
    path("api/reception/appointments/today/", receptionist_today_appointments_board, name="reception-appointments-today"),
    path("api/appointments/next-token/", appointment_next_token, name="appointment-next-token"),
    path("api/appointments/book/", appointment_book, name="appointment-book"),
    path("api/appointments/pause-current/", appointment_pause_current, name="appointment-pause-current"),
    path("api/appointments/add-emergency/", appointment_add_emergency, name="appointment-add-emergency"),
    path("api/doctors/day-unavailable/", doctor_day_unavailable_reschedule, name="doctor-day-unavailable"),
    path("api/reception/day-reschedules/pending/", receptionist_pending_day_reschedules, name="reception-day-reschedules-pending"),
    path("api/reception/day-reschedules/<int:request_id>/decide/", receptionist_decide_day_reschedule, name="reception-day-reschedules-decide"),
    path("api/appointments/<int:appointment_id>/complete/", appointment_complete, name="appointment-complete"),
    path("api/appointments/<int:appointment_id>/reschedule/", appointment_reschedule, name="appointment-reschedule"),
    path("api/appointments/<int:appointment_id>/cancel/", appointment_cancel, name="appointment-cancel"),
    path("api/appointments/queue-status/", queue_board, name="appointments-queue-status"),
    path("api/queue/board/", queue_board, name="queue-board"),
    path("api/queue/call-next/", queue_call_next, name="queue-call-next"),
    path("api/queue/appointment/<int:appointment_id>/called/", queue_mark_called, name="queue-mark-called"),
    path("api/queue/<int:queue_item_id>/skip/", queue_skip, name="queue-skip"),
    path("api/queue/<int:queue_item_id>/recall/", queue_recall, name="queue-recall"),
    path("api/queue/<int:queue_item_id>/no-show/", queue_no_show, name="queue-no-show"),
    path("api/consultations/appointment/<int:appointment_id>/draft/", consultation_save_draft, name="consultation-save-draft"),
    path("api/consultations/<int:consultation_id>/finalize/", consultation_finalize, name="consultation-finalize"),
    path("api/consultations/appointment/<int:appointment_id>/", consultation_get, name="consultation-get"),
    path("api/consultations/appointment/<int:appointment_id>/context/", consultation_context, name="consultation-context"),
    path("api/consultations/<int:consultation_id>/vitals/", vitals_record, name="vitals-record"),
    path("api/consultations/<int:consultation_id>/amend/", consultation_amend, name="consultation-amend"),
    path("api/consultations/<int:consultation_id>/amendments/", consultation_amendment_history, name="consultation-amendments"),
    path("api/consultations/<int:consultation_id>/prescription/", prescription_issue, name="prescription-issue"),
    path("api/consultations/<int:consultation_id>/prescription/update/", prescription_update, name="prescription-update"),
    path("api/consultations/<int:consultation_id>/prescription/get/", prescription_get, name="prescription-get"),
    path("api/consultations/<int:consultation_id>/appointment/next-patient/", appointment_complete_after_prescription, name="appointment-next-patient"),
    path("api/prescriptions/history/", prescription_history_by_patient, name="prescription-history-by-patient"),
    path("consultations/<int:consultation_id>/prescription/print/", prescription_print, name="prescription-print"),
    path("api/consultations/<int:consultation_id>/orders/", medical_order_create, name="order-create"),
    path("api/patients/<int:patient_id>/orders/", medical_order_create_for_patient, name="order-create-for-patient"),
    path("api/patients/<int:patient_id>/orders/context/", patient_medical_order_context, name="patient-medical-order-context"),
    path("api/consultations/<int:consultation_id>/orders/list/", medical_order_list, name="order-list"),
    path("api/consultations/<int:consultation_id>/billing/handoff/", billing_handoff_create, name="billing-handoff-create"),
    path("api/billing/ledger/by-opd/", billing_ledger_by_opd_get, name="billing-ledger-by-opd-get"),
    path("api/billing/ledger/by-opd/create/", billing_ledger_by_opd_create, name="billing-ledger-by-opd-create"),
    path("api/billing/ledger/<int:ledger_id>/line-items/", billing_ledger_add_line_item, name="billing-ledger-add-line-item"),
    path("api/billing/ledger/<int:ledger_id>/line-items/<int:line_item_id>/remove/", billing_ledger_remove_line_item, name="billing-ledger-remove-line-item"),
    path("api/billing/ledger/<int:ledger_id>/rct-case-amount/", billing_ledger_get_rct_case_amount, name="billing-ledger-rct-case-amount"),
    path("api/billing/ledger/<int:ledger_id>/repeat-fee-decision/", billing_ledger_repeat_fee_decision, name="billing-ledger-repeat-fee-decision"),
    path("api/billing/ledger/<int:ledger_id>/finalize/", billing_ledger_finalize, name="billing-ledger-finalize"),
    path("api/billing/invoice/<int:invoice_id>/", billing_invoice_get, name="billing-invoice-get"),
    path("api/billing/invoice/<int:invoice_id>/mark-paid-upi/", billing_invoice_mark_paid_upi, name="billing-invoice-mark-paid-upi"),
    path("api/billing/invoice/<int:invoice_id>/void/", billing_invoice_void, name="billing-invoice-void"),
    path("api/billing/invoice/<int:invoice_id>/update/", billing_invoice_update, name="billing-invoice-update"),
    path("api/billing/invoices/live/", billing_invoice_live_feed, name="billing-invoice-live-feed"),
    path("api/billing/invoices/history/", billing_invoice_history_by_patient, name="billing-invoice-history"),
    path("api/billing/invoice/<int:invoice_id>/pdf/", billing_invoice_pdf_download, name="billing-invoice-pdf"),
    path("billing/invoice/<int:invoice_id>/print/", billing_invoice_print, name="billing-invoice-print"),
    path("api/billing/handoffs/<int:handoff_id>/send/", billing_handoff_send, name="billing-handoff-send"),
    path("api/billing/reconcile/", billing_handoff_reconcile, name="billing-reconcile"),
    path("users/manage/", user_role_management, name="user-role-management"),
    path("api/users/create/", user_create, name="user-create"),
    path("api/users/assign-role/", user_assign_role, name="user-assign-role"),
    path("api/users/delete/", user_delete, name="user-delete"),
    path("api/roles/delete/", role_delete, name="role-delete"),
    path("api/admin/clinic-settings/update/", clinic_settings_update, name="clinic-settings-update"),
    path("api/admin/doctor-profile/update/", admin_doctor_profile_update, name="admin-doctor-profile-update"),
    path("api/admin/software/reset/", admin_software_reset, name="admin-software-reset"),
    path("api/users/profile/", user_profile_get, name="user-profile-get"),
    path("api/users/profile/update/", user_profile_update, name="user-profile-update"),
]
