from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import (
    appointment_book,
    appointment_cancel,
    appointment_complete,
    appointment_reschedule,
    billing_handoff_create,
    billing_handoff_reconcile,
    billing_handoff_send,
    consultation_amend,
    consultation_amendment_history,
    consultation_finalize,
    consultation_get,
    consultation_save_draft,
    health,
    health_live,
    health_ready,
    home,
    medical_order_create,
    medical_order_list,
    patient_register,
    patient_register_form,
    patient_opd_history_view,
    patient_search,
    patient_update,
    incident_create_view,
    incident_list_view,
    incident_resolve_view,
    observability_snapshot_view,
    report_export_download,
    report_export_generate,
    report_export_list,
    prescription_print,
    prescription_get,
    prescription_issue,
    pharmacist_workbench,
    queue_board,
    queue_call_next,
    queue_no_show,
    queue_recall,
    queue_skip,
    receptionist_workbench,
    rbac_bootstrap,
    schedule_upsert,
    doctor_workbench,
    doctor_today_appointments,
    dashboard_daily_metrics,
    tomorrow_reminder_report_view,
    user_assign_role,
    user_create,
    user_role_management,
    vitals_record,
)

urlpatterns = [
    path("", home, name="home"),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("health/", health, name="health"),
    path("health/live/", health_live, name="health-live"),
    path("health/ready/", health_ready, name="health-ready"),
    path("workbench/reception/", receptionist_workbench, name="workbench-reception"),
    path("workbench/doctor/", doctor_workbench, name="workbench-doctor"),
    path("workbench/pharmacy/", pharmacist_workbench, name="workbench-pharmacy"),
    path("api/rbac/bootstrap/", rbac_bootstrap, name="rbac-bootstrap"),
    path("patients/register/", patient_register_form, name="patient-register-form"),
    path("api/patients/register/", patient_register, name="patient-register"),
    path("api/patients/<int:patient_id>/update/", patient_update, name="patient-update"),
    path("api/patients/<int:patient_id>/opd-history/", patient_opd_history_view, name="patient-opd-history"),
    path("api/patients/search/", patient_search, name="patient-search"),
    path("api/reports/tomorrow-patients/", tomorrow_reminder_report_view, name="report-tomorrow-patients"),
    path("api/reports/dashboard/daily-metrics/", dashboard_daily_metrics, name="dashboard-daily-metrics"),
    path("api/reports/exports/generate/", report_export_generate, name="report-export-generate"),
    path("api/reports/exports/list/", report_export_list, name="report-export-list"),
    path("api/reports/exports/<int:export_id>/download/", report_export_download, name="report-export-download"),
    path("api/observability/snapshot/", observability_snapshot_view, name="observability-snapshot"),
    path("api/incidents/create/", incident_create_view, name="incident-create"),
    path("api/incidents/<int:incident_id>/resolve/", incident_resolve_view, name="incident-resolve"),
    path("api/incidents/list/", incident_list_view, name="incident-list"),
    path("api/doctors/schedule/upsert/", schedule_upsert, name="schedule-upsert"),
    path("api/doctors/appointments/today/", doctor_today_appointments, name="doctor-appointments-today"),
    path("api/appointments/book/", appointment_book, name="appointment-book"),
    path("api/appointments/<int:appointment_id>/complete/", appointment_complete, name="appointment-complete"),
    path("api/appointments/<int:appointment_id>/reschedule/", appointment_reschedule, name="appointment-reschedule"),
    path("api/appointments/<int:appointment_id>/cancel/", appointment_cancel, name="appointment-cancel"),
    path("api/queue/board/", queue_board, name="queue-board"),
    path("api/queue/call-next/", queue_call_next, name="queue-call-next"),
    path("api/queue/<int:queue_item_id>/skip/", queue_skip, name="queue-skip"),
    path("api/queue/<int:queue_item_id>/recall/", queue_recall, name="queue-recall"),
    path("api/queue/<int:queue_item_id>/no-show/", queue_no_show, name="queue-no-show"),
    path("api/consultations/appointment/<int:appointment_id>/draft/", consultation_save_draft, name="consultation-save-draft"),
    path("api/consultations/<int:consultation_id>/finalize/", consultation_finalize, name="consultation-finalize"),
    path("api/consultations/appointment/<int:appointment_id>/", consultation_get, name="consultation-get"),
    path("api/consultations/<int:consultation_id>/vitals/", vitals_record, name="vitals-record"),
    path("api/consultations/<int:consultation_id>/amend/", consultation_amend, name="consultation-amend"),
    path("api/consultations/<int:consultation_id>/amendments/", consultation_amendment_history, name="consultation-amendments"),
    path("api/consultations/<int:consultation_id>/prescription/", prescription_issue, name="prescription-issue"),
    path("api/consultations/<int:consultation_id>/prescription/get/", prescription_get, name="prescription-get"),
    path("consultations/<int:consultation_id>/prescription/print/", prescription_print, name="prescription-print"),
    path("api/consultations/<int:consultation_id>/orders/", medical_order_create, name="order-create"),
    path("api/consultations/<int:consultation_id>/orders/list/", medical_order_list, name="order-list"),
    path("api/consultations/<int:consultation_id>/billing/handoff/", billing_handoff_create, name="billing-handoff-create"),
    path("api/billing/handoffs/<int:handoff_id>/send/", billing_handoff_send, name="billing-handoff-send"),
    path("api/billing/reconcile/", billing_handoff_reconcile, name="billing-reconcile"),
    path("users/manage/", user_role_management, name="user-role-management"),
    path("api/users/create/", user_create, name="user-create"),
    path("api/users/assign-role/", user_assign_role, name="user-assign-role"),
]
